### PR TITLE
fix how tests are run for many features

### PR DESCRIPTION
**Pull request by ahdinosaur**
runs each feature as a separate tape test harness.

this means there is multiple prelude and closing statements, hmm. also wonder if i'm returning the correct exit code.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
linting is failing :(

**Comment by ahdinosaur** [comment]
fixed.

also i started experimenting with a crazy `pull-stream` replacement to `tape`: [`pull-test`](http://github.com/ahdinosaur/pull-test), which would make this all way better. hehe soon, but not meow. :stuck_out_tongue:

**Comment by yoshuawuyts** [comment]
Mostly LGTM! - quick check: does `t.plan()` for steps still work in this scenario? no biggy if it doesn't

**Comment by ahdinosaur** [comment]
yeah, it's all still `tape`, so nothing changed there.

**Comment by ahdinosaur** [comment]
if you mean "the scenario in which we move to `pull-test`": see https://github.com/ahdinosaur/pull-test/issues/4.

**Comment by yoshuawuyts** [comment]
Cool LGTM then. Not sure what the patch level is for this; go ahead and release the version you think is cool :ok_hand:

**Comment by ahdinosaur** [comment]
released as `2.0.2`, since this was really a bug that caused an error when you had more than one `.feature` file.

**Pull request merged**
